# Armor Stand Tools
# von St3venAU
# St3venAU@gmail.com
#
# Übersetzung: Andre_601
# Andre601.com
#
# Hauptconfig
#
# Datei erstellt von: v3.5.0
# (Wenn das nicht die Version ist, die du nutzt, solltest du diese Datei löschen, damit eine neue
#  generiert werden kann. Es gibt möglicherweise neue Optionen)
#
# Features:
#   - Rüstungsständer erschaffen
#   - Rüstungsständer benennen
#   - Ändere: Gravitation, Sichtbarkeit, Arme, Platte, Grösse, Unzerstörbarkeit, Ausrüstung sichern
#   - Manipuliere die Position von Kopf, Körper, Arme und Beine
#   - Volle Kontrolle über die Ausrüstung des Rüstungsständers (Rüstung und Items in den Händen.)
#   - Rüstungsständer klonen-Tool
#   - Befehlsblock erstellen-Tool: Erstellt einen Befehlsblock mit dem Befehl, welcher den Rüstungsständer
#     in seinem jetzigen Zustand spawnt.
#   - Spielerkopf-Tool: Setzt den Kopf des spezifizierten Spielers.
#   - Support für WorldGuard-Regionen
#   - Veränderbare Sprach config.
#
# Befehle:
#   /astools                        Gib dirselber alle Rüstungsständer-tools (Hinweis: Leert dein Inventar)
#   /astools reload                 Laded die config des plugins neu.
#   /ast                            Alias für /astools.
#   /ascmd assign console <command> Ordne einen Konsolen-Befehl dem nahsten Rüstungsständer zu (innerhalb von 4 Blöcken)
#   /ascmd assign player <command>  Ordne einen Spieler-Befehl dem nahsten Rüstungsständer zu.
#   /ascmd remove                   Entferne den Befehl vom nahsten Rüstungsständer.
#   /ascmd view                     Zeige den Befehl vom nahsten Rüstungsständer
#   /ascmd cooldown <ticks>         Setze den cooldown für den Befehl vom nahsten Rüstungsständer. (Dies überschreibt den standart cooldown in der config.yml)
#   /ascmd cooldown remove          Entfernt den cooldown für den Befehl vom nahsten Rüstungsständer. (Der normale cooldown in der config.yml wird verwendet)
#   Hinweis: Befehle können %player% enthalten, welches bei ausführung mit dem Spielername ausgetauscht wird.
#
# Permissions:
#   astools.command                 Recht für den Befehl /astools
#   astools.reload                  Recht für den Befehl /astools reload
#   astools.use                     Recht zum verwenden aller tools (Mit ausnahme der unteren, welche eigene Permissions haben)
#   astools.clone                   Recht zum verwenden des Klon-Tool (Klont den Rüstungsständer ohne die benötigten Materialien)
#   astools.summon                  Recht zum verwenden des Erschaffen-Tool (Erschafft einen Rüstungsständer ohne die benötigten Materialien)
#   astools.head                    Recht zum verwenden des Spielerkopf-Tool (Fähigkeit, einen Spielerkopf zu bestimmen)
#   astools.cmdblock                Recht zum verwenden des Speichern-Tool (Erstellt einen Befehlsblock)
#   astools.ascmd.assign.console    Recht zum zuordnen einens Konsolen-Befehls zu einem Rüstungsständer
#   astools.ascmd.assign.player     Recht zum zuordnen einens Spieler-Befehls zu einem Rüstungsständer
#   astools.ascmd.remove            Recht zum entfernen einens Befehls von einem Rüstungsständer
#   astools.ascmd.view              Recht zum sehen einens Befehls von einem Rüstungsständer
#   astools.ascmd.execute           Recht zum ausführen eines Befehls (Bei rechtsklick)
#   astools.bypass-wg-flag          Recht zum umgehen von AST's eigener WorldGuard flag (Siehe unten für mehr details)
#
# WorldGuard integration:
#   - Wenn ein Spieler nicht die Baurechte für eine Region hat, wird diesem auch das verwenden von AST in dieser Region verweigert.
#   - Zusätzlich gibt es noch eine eigene flag namens 'ast' welche standartmässig auf Erlauben gesetzt ist, kann aber zu verweigern
#     gesetzt werden, wenn du eine Region haben möchtest, in welcher Spieler bauen können, aber nicht AST verwenden sollen.
#   - Die ast WorldGuard flag wird ignoriert, wenn der Spieler die astools.bypass-wg-flag Berechtigung hat. Dies bedeutet, dass ein
#     Spieler mit dieser Berechtigung AST in WorldGuard Regionen verwenden kann, selbst wenn diese die ast flaf auf verweigern haben.
#   - Die ast WorldGuard flag wird auch ignoriert, wenn der Spieler OP hat.
#
# Dies sind die Standarts zum Erstellen eines neuen Rüstungsständers mit dem /astools (oder /ast) Rüstungsständers
# Der Helm, Brustplatte, Hosen, Schuhe und inHand-Items sind so gesetzt: MATERIAL Datenwert
# Bsp: Um standartmässig rote Wolle in der Hand vom Rüstungsständer zu haben: inHand: WOOL 14
#
integrateWithWorldGuard: true
allowMovingStandsBetweenWorlds: false
deactivateToolsOnWorldChange: true
requireCreativeForSaveAsCmdBlock: false
defaultASCmdCooldownTicks: 0
bypassWorldguardForASCmdExecution: false
# Unkommentiere den unteren Bereich um Spielern das verwenden bestimmter Befehle zu verweigern, wenn diese AST Tools im Inventar haben
# Füge so viele Befehle hinzu wie du willst. Nur das erste Wort eines Befehls ist benötigt. Alles nach dem ersten leerschlag wird ignoriert.
#deniedCommandsWhileUsingTools:
#  - sell
helmet: AIR 0
chest: AIR 0
pants: AIR 0
boots: AIR 0
inHand: AIR 0
inOffHand: AIR 0
isVisible: true
isSmall: false
hasArms: true
hasBasePlate: false
hasGravity: false
name: ''
invulnerable: false
equipmentLock: false
enableTool:
  headX: true
  headY: true
  headZ: true
  lArmX: true
  lArmY: true
  lArmZ: true
  rArmX: true
  rArmY: true
  rArmZ: true
  moveX: true
  moveY: true
  moveZ: true
  lLegX: true
  lLegY: true
  lLegZ: true
  rLegX: true
  rLegY: true
  rLegZ: true
  bodyX: true
  bodyY: true
  bodyZ: true
  summon: true
  gui: true
  rotat: true
  gui_clone: true
  gui_save: true
  gui_invis: true
  gui_size: true
  gui_base: true
  gui_grav: true
  gui_arms: true
  gui_name: true
  gui_slots: true
  gui_pHead: true
  gui_invul: true
  gui_move: true
  gui_glow: true
